# hw1_1 정준호

## a_tensor_initialization

In [1]:
import torch

In [2]:
# torch.Tensor class
t1 = torch.Tensor([1, 2, 3], device = 'cpu')
print(t1.dtype)
print(t1.device)
print(t1.requires_grad)
print(t1.size())
print(t1.shape)

# GPU 가지고 있을시
# t1_cuda = t1.to(torch.device('cuda'))
# 또는
# t1_cuda = t1.cuda()
t1_cpu = t1.cpu()

torch.float32
cpu
False
torch.Size([3])
torch.Size([3])


In [3]:
#torch.tensor function
t2 = torch.tensor([1, 2, 3], device = 'cpu')
print(t2.dtype)
print(t2.device)
print(t2.requires_grad)
print(t2.size())
print(t2.shape)

# GPU 가지고 있을시
# t1_cuda = t1.to(torch.device('cuda'))
# 또는
# t1_cuda = t1.cuda()
t1_cpu = t1.cpu()

torch.int64
cpu
False
torch.Size([3])
torch.Size([3])


In [4]:
a1 = torch.tensor(1)
print(a1.shape, a1.ndim)

torch.Size([]) 0


In [5]:
a2 = torch.tensor([1])
print(a2.shape, a2.ndim)

torch.Size([1]) 1


In [6]:
a3 = torch.tensor([1, 2, 3, 4, 5])
print(a3.shape, a3.ndim)

torch.Size([5]) 1


In [7]:
a4 = torch.tensor([[1], [2], [3], [4], [5]])
print(a4.shape, a4.ndim)

torch.Size([5, 1]) 2


In [8]:
a5 = torch.tensor([
    [1, 2],
    [3, 4],
    [5, 6]
])
print(a5.shape, a5.ndim)

torch.Size([3, 2]) 2


In [9]:
a6 = torch.tensor([
    [[1], [2]],
    [[3], [4]],
    [[5], [6]]
])
print(a6.shape, a6.ndim)

torch.Size([3, 2, 1]) 3


In [10]:
a7 = torch.tensor([
    [[[1], [2]]],
    [[[3], [4]]],
    [[[5], [6]]]
])
print(a7.shape, a7.ndim)

torch.Size([3, 1, 2, 1]) 4


In [11]:
a8 = torch.tensor([
    [[[1, 2, 3], [2, 3, 4]]],
    [[[3, 1, 1], [4, 4, 5]]],
    [[[5, 6, 2], [6, 3, 1]]]
])
print(a8.shape, a8.ndim)

torch.Size([3, 1, 2, 3]) 4


In [12]:
a9 = torch.tensor([
    [[[[1], [2], [3]], [[2], [3], [4]]]],
    [[[[3], [1], [1]], [[4], [4], [5]]]],
    [[[[5], [6], [2]], [[6], [3], [1]]]]
])
print(a9.shape, a9.ndim)

torch.Size([3, 1, 2, 3, 1]) 5


In [13]:
a10 = torch.tensor([
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
])
print(a10.shape, a10.ndim)

torch.Size([4, 5]) 2


In [14]:
# a11 = torch.tensor([
#     [[[1, 2, 3], [4, 5]]],
#     [[[1, 2, 3], [4, 5]]],
#     [[[1, 2, 3], [4, 5]]],
#     [[[1, 2, 3], [4, 5]]],
# ])
# print(a11.shape, a11.ndim)

# # 이 코드는 오류가 뜬다. 이유는 기대하고 있던 dim3과 다른 길이인 length 2가 왔기 때문이다

## b_tensor_initialization_copy

In [15]:
import torch
import numpy as np

In [16]:
l1 = [1, 2, 3]
t1 = torch.Tensor(l1)

l2 = [1, 2, 3]
t2 = torch.tensor(l2)

l3 = [1, 2, 3]
t3 = torch.as_tensor(l3)   # as_tensor는 가능하면 공유 필요하면 복사, 
                           # 리스트는 버퍼공유 불가이므로 결국 복사 발생

l1[0] = 100
l2[0] = 100
l3[0] = 100

print(t1)
print(t2)
print(t3)

# 고찰 결과
# 파이썬의 list는 ndarray와 다르게 메모리 버퍼를 적접 공유할 수 없다. 
# 따라서 리스트를 넘겨주면, PyTorch는 내부적으로 리스트 내용을 복사해서 새로운 텐서를 
# 만들기 때문에 리스트의 값을 변경해도 tensor에는 반영이 안되는 것이다.

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])


In [17]:
l4 = np.array([1, 2, 3])
t4 = torch.Tensor(l4)

l5 = np.array([1, 2, 3])
t5 = torch.tensor(l5)

l6 = np.array([1, 2, 3])
t6 = torch.as_tensor(l6)

l4[0] = 100
l5[0] = 100
l6[0] = 100

print(t4)
print(t5)
print(t6)

# 고찰 결과
# torch.Tensor와 torch.tensor는 항상 복사한다.
# torch.as_tensor는 가능하면 공유, 필요하면 복사를 한다
# torch.as_tensor와 비슷한 함수로는 torch.from_numpy(ndarray)가있는데 이는 무조건 메모리를 공유한다

tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)
tensor([100,   2,   3], dtype=torch.int32)


## c_tensor_initialization_constant_values

In [18]:
t1 = torch.ones(size=(5,))  # or torch.ones(5)
# 콤마가 들어가는 이유?
# => size는 정수 튜플이나 정수 리스트가 들어가야함. 따라서 5, 로 길이가 5인 1차원 텐서를 만든다 

t1_like = torch.ones_like(input=t1) # ones_like(t1)은 t1과 shape이 같은 1로 이루어진 텐서를 만든다
print(t1)
print(t1_like)

tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.])


In [19]:
t2 = torch.zeros(6)     # or torch.zeros(size=(6,))
                        # 콤마가 들어가는 이유?
                        # => size는 정수 튜플이나 정수 리스트가 들어가야함. 따라서 5, 로 길이가 5인 1차원 텐서를 만든다

t2_like = torch.zeros_like(t2)   # t2와 같은 shape의 0으로 구성된 텐서를 만든다
print(t2)
print(t2_like)

tensor([0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0.])


In [20]:
t3 = torch.empty(4)
t3_like = torch.empty_like(t3) # t3와 같은 shape의 비어있는 텐서를 만든다
print(t3)
print(t3_like)

# 이 코드는 실행할 때 마다 다른 값이나옴
# 그 이유는 empty는 비어있는 텐서를 만드는데 즉, 메모리 공간만 잡아놓고, 안에 든 값을 초기화 하지 않는다
# 따라서 잡아놓은 메모리에 남아있던 쓰레기 값이 들어가게 되어 출력결과가 다르게 보일 수 있음

tensor([1., 0., 0., 0.])
tensor([-4.2653e-14,  1.5975e-42,  0.0000e+00,  0.0000e+00])


In [21]:
t4 = torch.eye(3)
print(t4)

# torch.eye(n)은 n x n의 대각성분이 1인 텐서를 만든다

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


## d_tensor_initialization_random_values

In [22]:
import torch

In [23]:
t1 = torch.randint(low=10, high=20, size=(1, 2))
print(t1)

# torch.randint(low, high, size)
# [low, high) 으로 low이상 high미만으로 이루어진 정수를 size에 맞는 텐서를 반환한다

tensor([[15, 13]])


In [24]:
t2 = torch.rand(size=(1, 3))
print(t2)

# torch.rand(size)
# 이것은 균등분포(uniform dstribution)를 따르고 구간 0이상 1미만에서 난수 추출

tensor([[0.0713, 0.3694, 0.2862]])


In [25]:
t3 = torch.randn(size=(1, 3))
print(t3)

# torch.randn(size)
# 표준 정규분포(Standard Normal distribution)에서 난수 생성
# 평균 = 0, 표준편차 = 1

tensor([[-0.7373,  0.1835,  0.4980]])


In [26]:
t4 = torch.normal(mean=10.0, std=1.0, size=(3, 2))
print(t4)

# torch.normal(mean, std, size)
# 일반 정규분포(normal distribution) 직접 분포도를 지정
# 위 예제는 평균 10, 편차 1을 따른다

tensor([[11.3764,  8.7332],
        [ 9.9501, 10.0081],
        [11.4023,  9.1393]])


In [27]:
t5 = torch.linspace(start=0.0, end=5.0, steps=3)
print(t5)

# torch.linspace(start, end, steps)
# 처음과 끝이 각각 start와 end값으로 이루어져있고 steps값만큼 길이를 만든다. 간격은알아서 조정된다.

tensor([0.0000, 2.5000, 5.0000])


In [28]:
t6 = torch.arange(5)
print(t6)

# torch.arange(n)
# 0부터 n-1까지의 정수를 순차적으로 넣어 텐서를 만든다

tensor([0, 1, 2, 3, 4])


In [29]:
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

# 랜덤으로 나오는 seed를 고정한다
# 즉, 일관된 랜덤 seed를 얻을 수 있어 실험을 할때 등등 일관적으로 훈련할 수 있다
# 개인적으로 찾아본결과 seed값은 0<=seed<2**32(약 42억)의 정수를 넣으면 되는것으로 알고 있다.
# 즉 seed는 약 42억개의 방의 열쇠와 같다.

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


In [30]:
torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)

# 위 셀의 결과와 같은 것을 볼 수 있다. 즉, seed값이 같으면 어디에서나 같은 방식으로 동작하는 코드이므로
# 일관된 결과를 얻을 수 있다.

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


## e_tensor_type_conversion

In [31]:
a = torch.ones((2, 3))
print(a)  # b와 같이 dtype이 같이 출력되는지 확인하기 위한 코드 추가
print(a.dtype)

b = torch.ones((2, 3), dtype=torch.int16)  # dtype 매개변수를 이용하여 데이터 타입을 지정한다
print(b)

torch.manual_seed(1729)  # (추가)20.이 텐서 모든값에 대해서 곱해지는지 밑에서 확인하기위해 seed를 고정
c = torch.rand((2, 3), dtype=torch.float64) * 20.  # 모든 값에 대해서 20이 곱해진다
print(c)

d = b.to(torch.int32)
print(d)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
torch.float32
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[10.0160,  9.3871,  7.4563],
        [17.3151, 14.5980,  6.0404]], dtype=torch.float64)
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)


In [32]:
# (추가)
# 이 코드는 위의 c에 해당하는 코드가 20이 전체 값에 대해서 곱해지는지 확인하기위해 seed를 지정하여 비교할 수 있도록 코드를 작성함
torch.manual_seed(1729)
print(torch.rand((2, 3), dtype=torch.float64))

tensor([[0.5008, 0.4694, 0.3728],
        [0.8658, 0.7299, 0.3020]], dtype=torch.float64)


In [33]:
# (추가)
# 교수님의 코드는 double_d와 short_e에 대하여 적혀있지만 각각의 텐서를 확인하기 위해 print구문을 추가하였다

double_d = torch.ones(10, 2, dtype=torch.double)  # torch.double은 torch.float64와 같음 64비트의 부동소수점 지원
short_e = torch.tensor([[1, 2]], dtype=torch.short)  # torch.short는 torch.int16와 같음 

print(double_d)
print("-" *40)
print(short_e)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)
----------------------------------------
tensor([[1, 2]], dtype=torch.int16)


In [34]:
double_d = torch.zeros(10, 2).double()
short_e = torch.ones(10, 2).short()

print(double_d)
print("-" *40)
print(short_e)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)
----------------------------------------
tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int16)


In [35]:
double_d = torch.zeros(10, 2).to(torch.double)
short_e = torch.ones(10, 2).to(dtype=torch.short)

print(double_d)
print("-" *40)
print(short_e)

# 고찰
# PyTorch에서 .to()연산자는 텐서의 속성을 바꿀 때 사용한다
# 예를 들어 dtype, device, memory format을 바꿀때 사용한다 각 예제는 다음과 같다
# .to(torch.double)
# .to("cuda")
# 둘다 사용할 경우 .to(dtype=torch.double, device="cuda")

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)
----------------------------------------
tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int16)


In [36]:
double_d = torch.zeros(10, 2).type(torch.double)
short_e = torch.ones(10, 2).type(dtype=torch.short)

print(double_d)
print("-" *40)
print(short_e)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)
----------------------------------------
tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int16)


In [37]:
print(double_d.dtype)
print(short_e.dtype)

torch.float64
torch.int16


In [38]:
double_f = torch.rand(5, dtype=torch.double)
short_g = double_f.to(torch.short)
print((double_f * short_g).dtype)
# memory format이 다른 텐서를 곱하는 경우 memory format이 큰 텐서의 dtype으로 지정됨

torch.float64


In [39]:
# 고찰
# 텐서의 타입을 바꾸는 방법은 다양하게 존재하며 편한것을 사용하면 될듯하다
# 개인적으론 .to()연산자를 사용하는것이 직관적이라 좋아하나 사람들마다 다 사용하는 방식이 다르므로
# 모든 방법을 익혀놓는것이 중요할 듯 하다

## f_tensor_operations

In [40]:
import torch

In [41]:
t1 = torch.ones(size=(2, 3))
t2 = torch.ones(size=(2, 3))
t3 = torch.add(t1, t2)
t4 = t1 + t2
print(t3)
print(t4)
# add를 하고 싶을때 두가지방법이 존재
# 1. torch.add()함수 사용
# 2. t1 + t2 그냥 더하기

tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])


In [42]:
# (추가)
# add하고자 하는 텐서의 shape이 맞지 않으면 어떻게 될까 궁금하여 shape을 다르게 해봄
# 생각했던대로 error가 떳고 shape맞을 경우에만 add가능함
# 연습코드에 지장이 없도록 주석리리

# t1 = torch.ones(size=(2, 3))
# t2 = torch.ones(size=(2, 2))
# t3 = torch.add(t1, t2)
# t4 = t1 + t2
# print(t3)
# print(t4)

In [43]:
t5 = torch.sub(t1, t2)
t6 = t1 - t2
print(t5)
print(t6)
# subtract 하고 싶을때 두가지방법이 존재
# 1. torch.sub()함수 사용
# 2. t1 - t2 그냥 기기

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [44]:
t7 = torch.mul(t1, t2)
t8 = t1 * t2
print(t7)
print(t8)
# 곱하고 싶을때 두가지방법이 존재
# 1. torch.mul()함수 사용
# 2. t1 * t2 그냥 곱하기

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [45]:
t9 = torch.div(t1, t2)
t10 = t1 / t2
print(t9)
print(t10)
# 나누고 싶을때 두가지방법이 존재
# 1. torch.div()함수 사용
# 2. t1 / t2 그냥 나누기

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


## g_tensor_operations_mm

In [46]:
import torch

In [47]:
t1 = torch.dot(                  # torch.dot은 1차원 텐서만 허용. 길이도 같아야함. 내적을 계산함
    torch.tensor([2, 3]), torch.tensor([2, 1])
)
print(t1, t1.size())

tensor(7) torch.Size([])


In [48]:
t2 = torch.randn(2, 3)
t3 = torch.randn(3, 2)
t4 = torch.mm(t2, t3)       # 행렬을 계산하는 함수 즉, 결과가 2 x 2텐서로 나옴
print(t4, t4.size())

tensor([[-1.1766, -0.3342],
        [-3.0611, -0.5943]]) torch.Size([2, 2])


In [49]:
t5 = torch.randn(10, 3, 4)
t6 = torch.randn(10, 4, 5)
t7 = torch.bmm(t5, t6)
print(t7.size())
# 배치단위로 행렬곱을 수행하는 예시이다
# 배치는 10이고 각각 3x4, 4x5 행렬을 가지고 있어서 연산수행한다
# torch.bmm()은 3차원 텐서만 지원한다
# 4차원 이상을 하고자 하면 torch.matmul() 또는 @연산자를 사용

torch.Size([10, 3, 5])


## h_tensor_operations_matmul

In [50]:
import torch

In [51]:
t1 = torch.randn(3)
t2 = torch.randn(3)
print(torch.matmul(t1, t2).size()) 
#matmul은 모든차원에 적용가능하고 자동적으로 브로드캐스팅 적용한다

# (추가) 브로드 캐스팅이란? (원소별 연산임 : 산술연산, 비교연산, 논리연산, 수학함수 등)
# => 크기가 다른 텐서끼리 연산할 때, 작은 텐서의 크기를 자동으로 확장해서 연산해주는 규칙
# 1. 같으면 그대로 연산 가능
# 2. rank가 더 작은 텐서의 앞쪽에 1을 채워넣고 비교하면서 텐서 확장
# 3. 둘 다 다르고 1도 아니면 에러발생
####주의 : 행렬 곱셈 : 브로드캐스팅은 마지막 두 차원을 행렬로 처리, 나머지 차원만 브로드캐스팅됨
####주의 : 행렬 전용 연산(torch.mm, torch.bmm) : 입력 차원이 딱 정해져 있어서 브로드캐스팅 불가

# (추가) matmul의 규칙
# 1D x 1D => 내적, 스칼라
# 2D x 2D => 행렬 곱(2D)
# 2D x 1D => 행렬-벡터 곱 (1D 벡터)
# 1D x 2D => 벡터-행렬 곱 (1D 벡터)
# N차원 => 마지막 두 축은 행렬 곱, 앞 축들은 브로드캐스팅

torch.Size([])


In [52]:
t3 = torch.randn(3, 4)
t4 = torch.randn(4)
print(torch.matmul(t3, t4).size())

# 위의 규칙을 따르면 2Dx1D이므로 3이 된다

torch.Size([3])


In [53]:
t5 = torch.randn(10, 3, 4)
t6 = torch.randn(4)
print(torch.matmul(t5, t6).size())

# 위의 규칙을 따르면 브로드캐스팅에 의해 t6는 (10, 1, 4)가 되고 총 계산결과 size는 (10, 3)이다

torch.Size([10, 3])


In [54]:
t7 = torch.randn(10, 3, 4)
t8 = torch.randn(10, 4, 5)
print(torch.matmul(t7, t8).size())

# 이 예시는 batch와 행렬 곱의 size가 맞아 떨어지므로 계산이 온전하게 잘 된다

torch.Size([10, 3, 5])


In [55]:
t9 = torch.randn(10, 3, 4)
t10 = torch.randn(4, 5)
print(torch.matmul(t9, t10).size())

# t10은 배치가 없으므로 브로드캐스팅에 의해 size가 (10, 4, 5)로 증가한다

torch.Size([10, 3, 5])


## i_tensor_broadcasting

In [56]:
import torch

In [57]:
t1 = torch.tensor([1.0, 2.0, 3.0])
t2 = 2.0
print(t1 * t2)

# 자동으로 t2를 브로드캐스팅할 수 있는 텐서로 변환하여 곱을 수행함

tensor([2., 4., 6.])


In [58]:
t3 = torch.tensor([[0, 1], [2, 4], [10, 10]])
t4 = torch.tensor([4, 5])
print(t3 - t4)

# 자동으로 t4를 브로드캐스팅할 수 있는 텐서로 변환하여 sub을 수행한다

tensor([[-4, -4],
        [-2, -1],
        [ 6,  5]])


In [59]:
t5 = torch.tensor([[1., 2.], [3., 4.]])
print(t5 + 2.0)
print(t5 - 2.0)
print(t5 * 2.0)
print(t5 / 2.0)

# 마찬가지로 2.0을 t5에 대해 연산을 할 수 있도록 브로드캐스티을 진행하여 연산을 수행한다

tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


In [60]:
def normalize(x):
    return x / 255

t6 = torch.randn(3, 28, 28)
print(normalize(t6).size())

# 브로드캐스팅 규칙에 의해 normalize(X)의 연산인 x / 255를 t6의 모든 값에 대해서 수행한다.
# 브로드캐스팅을 활용한 텐서연산이다.

torch.Size([3, 28, 28])


In [61]:
t7 = torch.tensor([[1, 2], [0, 3]])
t8 = torch.tensor([[3, 1]])
t9 = torch.tensor([[5], [2]])
t10 = torch.tensor([7])
print(t7 + t8)
print(t7 + t9)
print(t8 + t9)   # 각각 [[3, 1], [3, 1]]  // [[5, 5], [2, 2]] 로 확장된다
print(t7 + t10)

# 브로드 캐스팅으로 사이즈를 맞춰서 연산을 수행한다

tensor([[4, 3],
        [3, 4]])
tensor([[6, 7],
        [2, 5]])
tensor([[8, 6],
        [5, 3]])
tensor([[ 8,  9],
        [ 7, 10]])


In [62]:
t11 = torch.ones(4, 3, 2)
t12 = t11 * torch.rand(3, 2)
print(t12.shape)

# 브로드캐스팅에 의해 t11이 확장되어  연산수행이 가능해진다

torch.Size([4, 3, 2])


In [63]:
t13 = torch.ones(4, 3, 2)
t14 = t13 * torch.rand(3, 1)
print(t14.shape)

# torch.rand(3, 1)의 사이즈가 확장되어 (4, 3, 2)가 된다

torch.Size([4, 3, 2])


In [64]:
t15 = torch.ones(4, 3, 2)
t16 = t15 * torch.rand(1, 2)
print(t16.shape)

# torch.rand(1, 2)의 사이즈가 확자되어 (4, 3, 2)가 된다

torch.Size([4, 3, 2])


In [65]:
t17 = torch.ones(5, 3, 4, 1)
t18 = torch.rand(3, 1, 1)
print((t17 + t18).size())

# torch.rand(3, 1, 1)의 사이즈가 확장되어 (5, 3, 4, 1)이 된다

torch.Size([5, 3, 4, 1])


In [66]:
t19 = torch.empty(5, 1, 4, 1)
t20 = torch.empty(3, 1, 1)
print((t19 + t20).size())

# 먼저 t20이 확장되어 t20.shape이 (5, 3, 1, 1)이 된다
# 그 후 서로의 크기에 맞게 조정되어 (5, 3, 4, 1)이 된다

torch.Size([5, 3, 4, 1])


In [67]:
t21 = torch.empty(1)
t22 = torch.empty(3, 1, 7)
print((t21 + t22).size())

# torch.empty 역시 브로드캐스팅에 의해 확장되어 (3, 1, 7)이 된다

torch.Size([3, 1, 7])


In [68]:
t23 = torch.ones(3, 3, 3)
t24 = torch.ones(3, 1, 3)
print((t23 + t24).size())

# 브로드캐스팅에 의해 t24의 shape이 (3, 3, 3)이 된다

torch.Size([3, 3, 3])


In [69]:
# t25 = torch.empty(5, 2, 4, 1)
# t26 = torch.empty(3, 1, 1)
# print((t25 + t26).size())

# # 브로드캐스팅은 크기를 맞출려는 차원의 값이 1이어야 연산하고자하는 텐서의 크기에 맞출 수 있다
# # 하지만 이는 2와 3이므로 브로드캐스팅 규칙에 맞지않으므로 오류가 뜬다.

In [70]:
t27 = torch.ones(4) * 5
print(t27)

# 브로드캐스팅에 의해 5가 브로드캐스팅되어 연산이 가능해진다

tensor([5., 5., 5., 5.])


In [71]:
t28 = torch.pow(t27, 2)
print(t28)

# 거듭제곱도 브로드캐스팅 가능하므로 2가 확장되어 연산을 수행한다

tensor([25., 25., 25., 25.])


In [72]:
exp = torch.arange(1., 5.)
a = torch.arange(1., 5.)
t29 = torch.pow(a, exp)
print(t29)

# 연산하고자 하는 텐서의 shape이 같으므로 1, 2, 3, 5를 각각 1제곱 2제곱 3제곱 4제곱 5제곱을 하여 결과 도출한다

tensor([  1.,   4.,  27., 256.])


## j_tensor_indexing_slicing

In [73]:
import torch

In [74]:
x = torch.tensor(
    [[0, 1, 2, 3, 4],
     [5, 6, 7, 8, 9],
     [10, 11, 12, 13, 14]]
)

print(x[1])     # 원소는 이차원안의 리스트들이므로 인덱스 1번에 해당하는 [5, 6, 7, 8, 9]
print(x[:, 1])  # x[a, b]라 했을때 a는이차원안의 리스트, b는 해당 리스트안의 원소를 말한다.
                # 즉, 이차원의 모든원소에 대해서 1번인덱스를 추출해라 라는 뜻이다.
print(x[1, 2])
print(x[:, -1]) # -1은 뒤에서 첫번째 원소를 가리키므로 모든원소에 대해서 맨 뒤의 원소를 추출하라는 뜻이다

tensor([5, 6, 7, 8, 9])
tensor([ 1,  6, 11])
tensor(7)
tensor([ 4,  9, 14])


In [75]:
print(x[1:])       # 1번인덱스부터 전체를 출력하라는 뜻
print(x[1:, 3:])   # 1번인덱스부터 전체를 추출하고 해당 원소리스트에서도 3번인덱스부터 추출하라는 뜻

tensor([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])
tensor([[ 8,  9],
        [13, 14]])


In [76]:
y = torch.zeros((6, 6))
y[1:4, 2] = 1
print(y)   # 이차원에 대해서 1, 2, 3번 리스트 중에 2번 인덱스의 값만 1로 변경한다는 뜻이다

print(y[1:4, 1:4])   # 이차원에 대해서 1, 2, 3번 리스트에서 각각1, 2, 3번 인덱스를 추출한다는 뜻이다

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([[0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.]])


In [77]:
z = torch.tensor(
    [[1, 2, 3, 4],
     [2, 3, 4, 5],
     [5, 6, 7, 8]]
)
print(z[:2])
print(z[1:, 1:3])
print(z[:, 1:])

z[1:, 1:3] = 0
print(z)

# 위에서 설명했다시피 인덱스 규칙에 맞게 각각 출력하고 값을 변경하는 작업을 하는 코드이다

tensor([[1, 2, 3, 4],
        [2, 3, 4, 5]])
tensor([[3, 4],
        [6, 7]])
tensor([[2, 3, 4],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[1, 2, 3, 4],
        [2, 0, 0, 5],
        [5, 0, 0, 8]])


## k_tensor_reshaping

In [78]:
import torch

In [79]:
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = t1.view(3, 2)    
# 새로운 텐서를 만들지 않고 원래 데이터를 바라보는 새로운 뷰를 만듬.
# 즉, view()로 만든 텐서를 바꾸면 원본에도 영향이 감
t3 = t1.reshape(1, 6)
# contiguous하면 view() 처럼 동작
# contiguous하지 않으면 새로운 복사본을 만들어서 동작
print(t2)
print(t3)

# (추가) 각각 t2와 t3를 바꾸었을때 t1이 바뀌는지 확인하기 위한 코드 추가
t2[0] = torch.tensor([0, 0])
print(t1)
t3[0] = torch.tensor(5)
print(t1)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[0, 0, 3],
        [4, 5, 6]])
tensor([[5, 5, 5],
        [5, 5, 5]])


In [80]:
t4 = torch.arange(8).view(2, 4) # 길이가 8인 0부터 7인 텐서를 주어진 사이즈에 맞게 변환
t5 = torch.arange(6).view(2, 3) # 길이가 6인 0부터 5인 텐서를 주어진 사이즈에 맞게 변환
print(t4)
print(t5)

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[0, 1, 2],
        [3, 4, 5]])


In [81]:
t6 = torch.tensor([[[1], [2], [3]]])
t7 = t6.squeeze()  # 1인 차원 모두 제거
t8 = t6.squeeze(0) # dim 0의 차원 거거
print(t7)
print(t8)

# (추가) t6, t7, t8의 shape확인을 위해 코드 추가
print(t6.shape)
print(t7.shape)
print(t8.shape)

tensor([1, 2, 3])
tensor([[1],
        [2],
        [3]])
torch.Size([1, 3, 1])
torch.Size([3])
torch.Size([3, 1])


In [82]:
t9 = torch.tensor([1, 2, 3])
t10 = t9.unsqueeze(1) # 1차원의 위치에 차원 추가 (1로 추가한다)
print(t10)

# (추가) shape확인을 위한 코드 추가
print(t9.shape)
print(t10.shape)

tensor([[1],
        [2],
        [3]])
torch.Size([3])
torch.Size([3, 1])


In [83]:
t11 = torch.tensor(
    [[1, 2, 3],
     [4, 5, 6]]
)
t12 = t11.unsqueeze(1) # 1차원의 위치에 차원 추가 (1로 추가한다)
print(t11, t12.shape)

# (추가) shape확인을 위한 코드 추가
print(t11.shape)
print(t12.shape)

tensor([[1, 2, 3],
        [4, 5, 6]]) torch.Size([2, 1, 3])
torch.Size([2, 3])
torch.Size([2, 1, 3])


In [84]:
t13 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t14 = t13.flatten()  # flatten()은 여러차원을 1차원으로 펴서 벡터로 만듬
print(t14)

tensor([1, 2, 3, 4, 5, 6])


In [85]:
t15 = torch.tensor([[[1, 2],
                     [3, 4]],
                     [[5, 6],
                      [7, 8]]])
t16 = torch.flatten(t15)             # t15.flatten()과 같은 결과
t17 = torch.flatten(t15, start_dim=1)  # 0번쨰 차원은 그대로 고 1번째 차원부터 끝까지 flatten함

print(t16)
print(t17)

tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [86]:
t18 = torch.randn(2, 3, 5)
print(t18.shape)
print(torch.permute(t18, (2, 0, 1)).size())   # permute는 차원을 바꾸는 작업이다

torch.Size([2, 3, 5])
torch.Size([5, 2, 3])


In [87]:
t19 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t20 = torch.permute(t19, dims=(0, 1))
t21 = torch.permute(t19, dims=(1, 0))  # 행과 열을 서로 바꾼다. 즉 행렬 전치와 같다.
print(t20)
print(t21)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [88]:
t22 = torch.transpose(t19, 0, 1) 
# 모든 차원 텐서에서 사용 가능
# 임의의 두 차원을 서로 바꾼다.
# 원하는 아무 두 축을 바꿀 수 있다.
# permute(t19, dims=(0, 1)) 과 같다. 0, 1차원을 바꾼다는 뜻이다.
print(t22)

tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [89]:
t23 = torch.t(t19)
# 2차원 텐서에서만 사용 가능하다.
print(t23)

tensor([[1, 4],
        [2, 5],
        [3, 6]])


## l_tensor_concat

In [90]:
import torch

In [91]:
t1 = torch.zeros([2, 1, 3])
t2 = torch.zeros([2, 3, 3])
t3 = torch.zeros([2, 2, 3])
t4 = torch.cat([t1, t2, t3], dim=1) 
# torch.cat(tensors, dim)
# 여러 텐서를 지정한 차원을 따라 이어붙이는(concatenate)함수
# 붙이는 차원(dim)만 은 달라도 됨
# 나머지 모든 차원은 크기가 같아야함
print(t4.shape)

torch.Size([2, 6, 3])


In [92]:
t5 = torch.arange(0, 3)
t6 = torch.arange(3, 8)

t7 = torch.cat((t5, t6), dim=0)  # t5뒤에 t6를 이어 붙인다
print(t7.shape)
print(t7)

torch.Size([8])
tensor([0, 1, 2, 3, 4, 5, 6, 7])


In [93]:
t8 = torch.arange(0, 6).reshape(2, 3)
t9 = torch.arange(6, 12).reshape(2, 3)

t10 = torch.cat((t8, t9), dim=0)  # 2차원 텐서 병합으로써 dim=0으로 행방향으로 쌓는다
print(t10.size())
print(t10)

torch.Size([4, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])


In [94]:
t11 = torch.cat((t8, t9), dim=1)  # 2차원 텐서 병합으로써 dim=1으로 열방향으로 쌓는다
print(t11.size())
print(t11)

torch.Size([2, 6])
tensor([[ 0,  1,  2,  6,  7,  8],
        [ 3,  4,  5,  9, 10, 11]])


In [95]:
t12 = torch.arange(0, 6).reshape(2, 3)
t13 = torch.arange(6, 12).reshape(2, 3)
t14 = torch.arange(12, 18).reshape(2, 3)

t15 = torch.cat((t12, t13, t14), dim=0)  # dim = 0이므로 행방향으로 쌓는다
print(t15.size())
print(t15)

torch.Size([6, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])


In [96]:
t16 = torch.cat((t12, t13, t14), dim=1)  # dim = 1이므로 열방향으로 쌓는다
print(t16.size())
print(t16)

torch.Size([2, 9])
tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
        [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])


In [97]:
t17 = torch.arange(0, 6).reshape(1, 2, 3)
t18 = torch.arange(6, 12).reshape(1, 2, 3)

t19 = torch.cat((t17, t18), dim=0)  # dim=0이므로 0차원만 더하여 2행3열이 두개가 된다.
print(t19.size())
print(t19)

torch.Size([2, 2, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])


In [98]:
t20 = torch.cat((t17, t18), dim=1)  # dim=1이므로 1차원이 더해져 4행이 된다
print(t20.size())
print(t20)

torch.Size([1, 4, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]])


In [99]:
t21 = torch.cat((t17, t18), dim=2)  # dim=2이므로 2차원이 더해져서 총 6열이 된다
print(t21.size())
print(t21)

torch.Size([1, 2, 6])
tensor([[[ 0,  1,  2,  6,  7,  8],
         [ 3,  4,  5,  9, 10, 11]]])


## m_tensor_stacking

In [100]:
import torch

In [101]:
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])  
t2 = torch.tensor([[7, 8, 9], [10, 11, 12]])

t3 = torch.stack([t1, t2], dim=0)  
# 여러 텐서를 지정된(dim=0)차원에 새로운 차원으로 쌓아 올리는 함수
t4 = torch.cat([t1.unsqueeze(dim=0), t2.unsqueeze(dim=0)], dim=0)  
# torch.stack으로 만든 shape과 동일한 결과를 만들기위해 unsqueeze(dim=0)으로 차원생성후 concat
print(t3.shape, t3.equal(t4))  # t3.equal(t4)는 t3와 t4의 shape이 같은지 확인

torch.Size([2, 2, 3]) True


In [102]:
t5 = torch.stack([t1, t2], dim=1)
t6 = torch.cat([t1.unsqueeze(dim=1), t2.unsqueeze(dim=1)], dim=1) 
# dim=1에 차원이 추가됨
# 같은 행끼리 묶어서 나란히 들어간다
print(t5.shape, t5.equal(t6))

torch.Size([2, 2, 3]) True


In [103]:
# (추가) t5의 결과를 보기위함
print(t5)

tensor([[[ 1,  2,  3],
         [ 7,  8,  9]],

        [[ 4,  5,  6],
         [10, 11, 12]]])


In [104]:
t7 = torch.stack([t1, t2], dim=2)
t8 = torch.cat([t1.unsqueeze(dim=2), t2.unsqueeze(dim=2)], dim=2)  
# dim=2 위치에 새로운 차원을 추가하는것이다
# stack하는 방법과 unsqueeze하는 두가지 방법이 있다. 결과는 동일다다
print(t7.shape, t7.equal(t8))

torch.Size([2, 3, 2]) True


In [105]:
t9 = torch.arange(0, 3)
t10 = torch.arange(3, 6)
# 각각 size가 3인 텐서를 만든다
print(t9.size(), t10.size())

torch.Size([3]) torch.Size([3])


In [106]:
t11 = torch.stack((t9, t10), dim=0)  # dim 0 위치에 새로운 차원을 추가한다
print(t11.size())
print(t11)

torch.Size([2, 3])
tensor([[0, 1, 2],
        [3, 4, 5]])


In [107]:
t12 = torch.cat((t9.unsqueeze(0), t10.unsqueeze(0)), dim=0) # 위의 예제와 동일한 결과이다
print(t11.equal(t12))  # equal로 shape이 동일한지 확인

True


In [108]:
t13 = torch.stack((t9, t10), dim=1)  # dim 0 위치에 새로운 차원을 추가한다
print(t13.size())
print(t13)

torch.Size([3, 2])
tensor([[0, 3],
        [1, 4],
        [2, 5]])


In [109]:
t14 = torch.cat((t9.unsqueeze(1), t10.unsqueeze(1)), dim=1) # 위의 예제와 동일한 결과이다
print(t13.equal(t14))  # equal로 shape이 동일한지 확인

True


## n_tensor_vstack_hstack

In [110]:
import torch

In [111]:
t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([4, 5, 6])
t3 = torch.vstack((t1, t2))   
# dim = 0을 기준으로 쌓는다
# torch.vstack(tensors) == torch.cat(tensors, dim=0)
# 즉, 예제는 2D 텐서이므로 행을 기준으로 쌓는다.
print(t3)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [112]:
t4 = torch.tensor([[1], [2], [3]])
t5 = torch.tensor([[4], [5], [6]])
t6 = torch.vstack((t4, t5)) 
# dim = 0을 기준으로 쌓는다
# 즉, 예제는 2D 텐서이므로 행을 기준으로 쌓는다.
print(t6)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])


In [113]:
t7 = torch.tensor([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])
print(t7.shape)

t8 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t8.shape)

t9 = torch.vstack([t7, t8])  # dim=0을 기준으로 쌓으므로 채널축으로 쌓인다.
print(t9.shape)
print(t9)

torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([4, 2, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]])


In [114]:
t10 = torch.tensor([1, 2, 3])
t11 = torch.tensor([4, 5, 6])
t12 = torch.hstack((t10, t11))
# dim = 1을 기준으로 쌓는다
# torch.hstack(tensors) == torch.cat(tensors, dim=1)
print(t12)

tensor([1, 2, 3, 4, 5, 6])


In [115]:
t13 = torch.tensor([[1], [2], [3]])
t14 = torch.tensor([[4], [5], [6]])
t15 = torch.hstack((t13, t14))
print(t15)

tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [116]:
t16 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t16.shape)

t17 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t17.shape)

t18 = torch.hstack([t16, t17])  # dim = 1을 기준으로 쌓여서 hstack결과 shape이 2, 4, 3이 된다
print(t18.shape)
print(t18)

torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([2, 4, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [13, 14, 15],
         [16, 17, 18]],

        [[ 7,  8,  9],
         [10, 11, 12],
         [19, 20, 21],
         [22, 23, 24]]])


## 숙제 후기

In [117]:
# AI 에 관심이 생겨서 3학년 1학기부터 혼자 딥러닝 예습을 진행했었습니다.
    
# 미리 예습을 진행한 탓에 진도를 놓치지 않고 잘 따라갈 수 있었으며, 
# 제가 부족했던 부분에 대해 더 깊이 공부할 수 있었습니다.
    
# 특히 hw_01과제는 구현할때 굉장이 basic한 부분이므로 매우 중요하다는 것을 알고 있었습니다.

# 따라서 하나하나 타이핑하며 아는내용은 다시한번 복습하고 부족했던 부분은 더 확실히 짚고 넘어갔습니다.
# hw_01과제에서 특히 어려웠던 부분은 stack이었습니다. 차원이 변하여 텐서의 구조가 변하는데,
# 저는 이것을 시각화 하여 보고싶었습니다.

# 따라서 1차원 2차원 3차원은 shape의 변화에따라 텐서가 어떻게 변화는지 직접 생각해보며 그려봤지만
# 4차원부터는 매우 어려웠습니다.
    
# 단순히 shape이 변한다고 생각하고 넘어갈 수 있지만 저는 이것을 직접 변한걸 생각해보고 넘어가는것이
# 더 이해가 잘 될 것이라고 판단하였기 떄문에 이렇게 해보았습니다.

# 4차원부터는 직접 그리는것이 어려웠지만 이과정을 겪으므로써 확실하게 stack이 어떻게 동작하는지 알 수 있게 되었습니다.
# 예습하며 진행해볼때 텐서의 구조와 shape의 중요성을 굉장히 뼈저리게 느꼇던 저는 이번과제를 되게 열심히 하였습니다.